[package]
name = "koho"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
num-complex = "0.4.6"
rand = "0.9.0"
candle-core = "0.9.1"
candle-optimisers = { git = "https://github.com/KGrewal1/optimisers.git", version = "0.9.0" }
candle-nn = "0.9.1"
